//
//  NewCells.h
//  Lines
//
//  Created by Admin on 25.01.15.
//  Copyright (c) 2015 Hrach. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "Config.h"
#import "Colors.h"
#import "LinesBoard.h"
#import "MulticastDelegate.h"
#import "Protocols.h"

//mathematical object of the random cells generated by the game
@interface NewCells : NSObject
+(NewCells*) sharedNewCells;
// a multicast delegate to inform the NewCellsCells about the state change
@property (readonly) MulticastDelegate* multiCastDelegate;
//called on the object to update the cells
-(void) updateCellsWithInitializing:(BOOL) initializing;
//returns the cell state at place
-(CellState)getCellState:(NSInteger) place;
// sets the cell state at give plance, used for loading the info from a saved file
-(void)setCellStateAt:(NSInteger) position state:(CellState) cellState;
@end
